[project]
name = "uav-gc-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymavlink>=2.4.49",
]

[tool.mypy]
stubPath = "typings"

[[tool.mypy.overrides]]
module = ["pymavlink", "pymavlink.*"]
ignore_missing_imports = true
