"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class CSVMessage:
    def __init__(self, message_type, fmt, line) -> None:
        ...
    
    def get_type(self):
        ...
    
    def __str__(self) -> str:
        ...
    
    def get_fieldnames(self):
        ...
    
    def __getattr__(self, field):
        '''override field getter'''
        ...
    


class CSVFormat:
    def __init__(self, headings, messages, timestamp_expression=...) -> None:
        ...
    


class CSVReader:
    '''parse a CSV file'''
    def __init__(self, filename, zero_time_base=..., progress_callback=..., separator=..., message_type=..., timestamp_expression=...) -> None:
        ...
    
    def flightmode_list(self):
        ...
    
    def count_lines(self):
        ...
    
    def rewind(self):
        ...
    
    def name_to_id(self, name):
        ...
    
    def recv_msg(self):
        ...
    
    def recv_match(self, condition=..., type=..., blocking=...):
        '''recv the next message that matches the given condition
        type can be a string or a list of strings'''
        ...
    
    def check_condition(self, condition):
        '''check if a condition is true'''
        ...
    


if __name__ == "__main__":
    ...
