"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
FORMAT_TO_STRUCT = ...
MULT_TO_PREFIX = ...
def is_quiet_nan(val):
    '''determine if the argument is a quiet nan'''
    ...

class DFFormat:
    def __init__(self, type, name, flen, format, columns, oldfmt=...) -> None:
        ...
    
    def set_instance_field(self, instance_idx):
        '''set up the instance field for this format'''
        ...
    
    def set_unit_ids(self, unit_ids, unit_lookup):
        '''set unit IDs string from FMTU'''
        ...
    
    def set_mult_ids(self, mult_ids, mult_lookup):
        '''set mult IDs string from FMTU'''
        ...
    
    def get_unit(self, col):
        '''Return the unit for the specified field'''
        ...
    
    def __str__(self) -> str:
        ...
    


def to_string(s):
    '''desperate attempt to convert a string regardless of what garbage we get'''
    ...

def null_term(string):
    '''null terminate a string'''
    ...

class DFMessage:
    def __init__(self, fmt, elements, apply_multiplier, parent) -> None:
        ...
    
    def to_dict(self):
        ...
    
    def __getattr__(self, field):
        '''override field getter'''
        ...
    
    def __setattr__(self, field, value):
        '''override field setter'''
        ...
    
    def get_type(self):
        ...
    
    def __str__(self) -> str:
        ...
    
    def dump_verbose_bitmask(self, f, c, val, field_metadata):
        ...
    
    def dump_verbose(self, f):
        ...
    
    def get_msgbuf(self):
        '''create a binary message buffer for a message'''
        ...
    
    def get_fieldnames(self):
        ...
    
    def __getitem__(self, key):
        '''support indexing, allowing for multi-instance sensors in one message'''
        ...
    


class DFReaderClock:
    '''base class for all the different ways we count time in logs'''
    def __init__(self) -> None:
        ...
    
    def set_timebase(self, base):
        ...
    
    def message_arrived(self, m):
        ...
    
    def rewind_event(self):
        ...
    


class DFReaderClock_usec(DFReaderClock):
    '''DFReaderClock_usec - use microsecond timestamps from messages'''
    def __init__(self) -> None:
        ...
    
    def find_time_base(self, gps, first_us_stamp):
        '''work out time basis for the log - even newer style'''
        ...
    
    def rewind_event(self):
        '''reset state on rewind'''
        ...
    
    def type_has_good_TimeMS(self, type):
        '''The TimeMS in some messages is not from *our* clock!'''
        ...
    
    def should_use_msec_field0(self, m):
        ...
    
    def set_message_timestamp(self, m):
        ...
    


class DFReaderClock_msec(DFReaderClock):
    '''DFReaderClock_msec - a format where many messages have TimeMS in
    their formats, and GPS messages have a "T" field giving msecs'''
    def __init__(self) -> None:
        ...
    
    def find_time_base(self, gps, first_ms_stamp):
        '''work out time basis for the log - new style'''
        ...
    
    def rewind_event(self):
        '''reset state on rewind'''
        ...
    
    def set_message_timestamp(self, m):
        ...
    


class DFReaderClock_px4(DFReaderClock):
    '''DFReaderClock_px4 - a format where a starting time is explicitly
    given in a message'''
    def __init__(self) -> None:
        ...
    
    def find_time_base(self, gps):
        '''work out time basis for the log - PX4 native'''
        ...
    
    def set_px4_timebase(self, time_msg):
        ...
    
    def set_message_timestamp(self, m):
        ...
    
    def message_arrived(self, m):
        ...
    


class DFReaderClock_gps_interpolated(DFReaderClock):
    '''DFReaderClock_gps_interpolated - for when the only real references
    in a message are GPS timestamps'''
    def __init__(self) -> None:
        ...
    
    def rewind_event(self):
        '''reset counters on rewind'''
        ...
    
    def message_arrived(self, m):
        ...
    
    def gps_message_arrived(self, m):
        '''adjust time base from GPS message'''
        ...
    
    def set_message_timestamp(self, m):
        ...
    


class DFMetaData:
    '''handle dataflash messages metadata'''
    def __init__(self, parent) -> None:
        ...
    
    def reset(self):
        '''clear cached data'''
        ...
    
    @staticmethod
    def dot_pymavlink(*args):
        '''return a path to store pymavlink data'''
        ...
    
    @staticmethod
    def download_url(url):
        '''download a URL and return the content'''
        ...
    
    @staticmethod
    def download():
        ...
    
    def metadata_tree(self, verbose=...):
        ''' return a map between a log message and its metadata. May return
        None if data is not available '''
        ...
    
    def print_help(self, msg):
        '''print help for a log message'''
        ...
    
    def get_description(self, msg):
        '''get the description of a log message'''
        ...
    


class DFReader:
    '''parse a generic dataflash file'''
    def __init__(self) -> None:
        ...
    
    def init_clock_px4(self, px4_msg_time, px4_msg_gps):
        ...
    
    def init_clock_msec(self):
        ...
    
    def init_clock_usec(self):
        ...
    
    def init_clock_gps_interpolated(self, clock):
        ...
    
    def init_clock(self):
        '''work out time basis for the log'''
        ...
    
    def recv_msg(self):
        ...
    
    def recv_match(self, condition=..., type=..., blocking=..., strict=...):
        '''recv the next message that matches the given condition
        type can be a string or a list of strings'''
        ...
    
    def check_condition(self, condition):
        '''check if a condition is true'''
        ...
    
    def param(self, name, default=...):
        '''convenient function for returning an arbitrary MAVLink
           parameter with a default'''
        ...
    
    def flightmode_list(self):
        '''return an array of tuples for all flightmodes in log. Tuple is (modestring, t0, t1)'''
        ...
    
    def close(self):
        '''close the log file'''
        ...
    


class DFReader_binary(DFReader):
    '''parse a binary dataflash file'''
    def __init__(self, filename, zero_time_base=..., progress_callback=...) -> None:
        ...
    
    def rewind(self):
        '''rewind to start of log'''
        ...
    
    def init_arrays(self, progress_callback=...):
        '''initialise arrays for fast recv_match()'''
        ...
    
    def init_arrays_fast(self, progress_callback=...):
        '''initialise arrays for fast recv_match(), but with Cython'''
        ...
    
    def last_timestamp(self):
        '''get the last timestamp in the log'''
        ...
    
    def skip_to_type(self, type, strict=...):
        '''skip fwd to next msg matching given type set'''
        ...
    
    def find_unused_format(self):
        '''find an unused format code'''
        ...
    
    def add_format(self, fmt):
        '''add a new format'''
        ...
    
    def make_msgbuf(self, fmt, values):
        '''make a message buffer from a list of values'''
        ...
    
    def make_format_msgbuf(self, fmt):
        '''make a message buffer for a FMT message'''
        ...
    


def DFReader_is_text_log(filename):
    '''return True if a file appears to be a valid text log'''
    ...

class DFReader_text(DFReader):
    '''parse a text dataflash file'''
    def __init__(self, filename, zero_time_base=..., progress_callback=...) -> None:
        ...
    
    def rewind(self):
        '''rewind to start of log'''
        ...
    
    def init_arrays(self, progress_callback=...):
        '''initialise arrays for fast recv_match()'''
        ...
    
    def skip_to_type(self, type, strict=...):
        '''skip fwd to next msg matching given type set'''
        ...
    
    def last_timestamp(self):
        '''get the last timestamp in the log'''
        ...
    


if __name__ == "__main__":
    use_profiler = ...
    parse_messages = ...
    filename = ...
