"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class fgFDMError(Exception):
    '''fgFDM error class'''
    def __init__(self, msg) -> None:
        ...
    


class fgFDMVariable:
    '''represent a single fgFDM variable'''
    def __init__(self, index, arraylength, units) -> None:
        ...
    


class fgFDMVariableList:
    '''represent a list of fgFDM variable'''
    def __init__(self) -> None:
        ...
    
    def add(self, varname, arraylength=..., units=...):
        ...
    


class fgFDM:
    '''a flightgear native FDM parser/generator'''
    def __init__(self) -> None:
        '''init a fgFDM object'''
        ...
    
    def packet_size(self):
        '''return expected size of FG FDM packets'''
        ...
    
    def convert(self, value, fromunits, tounits):
        '''convert a value from one set of units to another'''
        ...
    
    def units(self, varname):
        '''return the default units of a variable'''
        ...
    
    def variables(self):
        '''return a list of available variables'''
        ...
    
    def get(self, varname, idx=..., units=...):
        '''get a variable value'''
        ...
    
    def set(self, varname, value, idx=..., units=...):
        '''set a variable value'''
        ...
    
    def parse(self, buf):
        '''parse a FD FDM buffer'''
        ...
    
    def pack(self):
        '''pack a FD FDM buffer from current values'''
        ...
    


