"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from math import *

"""
This type stub file was generated by pyright.
"""
def kmh(mps):
    '''convert m/s to Km/h'''
    ...

def altitude(SCALED_PRESSURE, ground_pressure=..., ground_temp=...):
    '''calculate barometric altitude'''
    ...

def altitude2(SCALED_PRESSURE, ground_pressure=..., ground_temp=...):
    '''calculate barometric altitude'''
    ...

def mag_heading(RAW_IMU, ATTITUDE, declination=..., SENSOR_OFFSETS=..., ofs=...):
    '''calculate heading from raw magnetometer'''
    ...

def mag_field_df(MAG, ofs=..., diagonals=..., offdiagonals=...):
    '''calculate magnetic field strength from raw magnetometer for DF '''
    ...

def mag_heading_df(MAG, ATT, declination=..., ofs=..., diagonals=..., offdiagonals=...):
    '''calculate heading from raw magnetometer'''
    ...

def gps_time_to_epoch(week, msec):
    '''convert GPS week and TOW to a time in seconds since 1970'''
    ...

def mag_heading_motors(RAW_IMU, ATTITUDE, declination, SENSOR_OFFSETS, ofs, SERVO_OUTPUT_RAW, motor_ofs):
    '''calculate heading from raw magnetometer'''
    ...

def mag_field(RAW_IMU, SENSOR_OFFSETS=..., ofs=...):
    '''calculate magnetic field strength from raw magnetometer'''
    ...

def mag_field_df(MAG, ofs=...):
    '''calculate magnetic field strength from raw magnetometer (dataflash version)'''
    ...

def get_motor_offsets(SERVO_OUTPUT_RAW, ofs, motor_ofs):
    '''calculate magnetic field strength from raw magnetometer'''
    ...

def mag_field_motors(RAW_IMU, SENSOR_OFFSETS, ofs, SERVO_OUTPUT_RAW, motor_ofs):
    '''calculate magnetic field strength from raw magnetometer'''
    ...

def angle_diff(angle1, angle2):
    '''show the difference between two angles in degrees'''
    ...

average_data = ...
def average(var, key, N):
    '''average over N points'''
    ...

derivative_data = ...
def second_derivative_5(var, key):
    '''5 point 2nd derivative'''
    ...

def second_derivative_9(var, key):
    '''9 point 2nd derivative'''
    ...

lowpass_data = ...
def lowpass(var, key, factor):
    '''a simple lowpass filter'''
    ...

def lpalpha(sample_rate_hz, cutoff_hz):
    '''find alpha for low pass filter'''
    ...

lowpass_hz_data = ...
def lowpassHz(var, key, sample_rate_hz, cutoff_hz):
    '''a simple lowpass filter with specified frequency'''
    ...

last_diff = ...
def diff(var, key):
    '''calculate differences between values'''
    ...

last_delta = ...
def delta(var, key, tusec=...):
    '''calculate slope'''
    ...

last_sum = ...
def sum(var, key):
    '''sum variable'''
    ...

last_integral = ...
def integral(var, key, timeus):
    '''integrate variable'''
    ...

def delta_angle(var, key, tusec=...):
    '''calculate slope of an angle'''
    ...

def roll_estimate(RAW_IMU, GPS_RAW_INT=..., ATTITUDE=..., SENSOR_OFFSETS=..., ofs=..., mul=..., smooth=...):
    '''estimate roll from accelerometer'''
    ...

def pitch_estimate(RAW_IMU, GPS_RAW_INT=..., ATTITUDE=..., SENSOR_OFFSETS=..., ofs=..., mul=..., smooth=...):
    '''estimate pitch from accelerometer'''
    ...

def rotation(ATTITUDE):
    '''return the current DCM rotation matrix'''
    ...

def mag_rotation(RAW_IMU, inclination, declination):
    '''return an attitude rotation matrix that is consistent with the current mag
       vector'''
    ...

def mag_pitch(RAW_IMU, inclination, declination):
    '''estimate pithc from mag'''
    ...

def mag_roll(RAW_IMU, inclination, declination):
    '''estimate roll from mag'''
    ...

def gravity(RAW_IMU, SENSOR_OFFSETS=..., ofs=..., mul=..., smooth=...):
    '''estimate pitch from accelerometer'''
    ...

def pitch_sim(SIMSTATE, GPS_RAW):
    '''estimate pitch from SIMSTATE accels'''
    ...

ORGN = ...
def get_origin():
    ...

def get_lat_lon_alt(MSG):
    '''gets lat and lon in radians and alt in meters from a position msg'''
    ...

def distance_two(MSG1, MSG2, horizontal=...):
    '''distance between two points'''
    ...

first_fix = ...
def distance_home(GPS_RAW):
    '''distance from first fix point'''
    ...

def sawtooth(ATTITUDE, amplitude=..., period=...):
    '''sawtooth pattern based on uptime'''
    ...

def rate_of_turn(speed, bank):
    '''return expected rate of turn in degrees/s for given speed in m/s and
       bank angle in degrees'''
    ...

def wingloading(bank):
    '''return expected wing loading factor for a bank angle in radians'''
    ...

def airspeed(VFR_HUD, ratio=..., used_ratio=..., offset=...):
    '''recompute airspeed with a different ARSPD_RATIO'''
    ...

def EAS2TAS(ARSP, GPS, BARO, ground_temp=...):
    '''EAS2TAS from ARSP.Temp'''
    ...

SSL_AIR_DENSITY = ...
C_TO_KELVIN = ...
ISA_LAPSE_RATE = ...
ISA_GAS_CONSTANT = ...
SSL_AIR_TEMPERATURE = ...
SSL_AIR_PRESSURE = ...
def SimpleAtmosphere(alt_km):
    ...

def eas2tas(alt_m, groundtemp=...):
    '''eas2tas from altitude in meters AMSL'''
    ...

def airspeed_tas(VFR_HUD, GLOBAL_POSITION_INT):
    '''airspeed as true airspeed from VFR_HUD and GLOBAL_POSITION_INT'''
    ...

def airspeed_ratio(VFR_HUD):
    '''recompute airspeed with a different ARSPD_RATIO'''
    ...

def airspeed_voltage(VFR_HUD, ratio=...):
    '''back-calculate the voltage the airspeed sensor must have seen'''
    ...

def earth_rates(ATTITUDE):
    '''return angular velocities in earth frame'''
    ...

def roll_rate(ATTITUDE):
    '''return roll rate in earth frame'''
    ...

def pitch_rate(ATTITUDE):
    '''return pitch rate in earth frame'''
    ...

def yaw_rate(ATTITUDE):
    '''return yaw rate in earth frame'''
    ...

def gps_velocity(GLOBAL_POSITION_INT):
    '''return GPS velocity vector'''
    ...

def gps_velocity_old(GPS_RAW_INT):
    '''return GPS velocity vector'''
    ...

def gps_velocity_body(GPS_RAW_INT, ATTITUDE):
    '''return GPS velocity vector in body frame'''
    ...

def earth_accel(IMU, ATT):
    '''return earth frame acceleration vector'''
    ...

def earth_gyro(IMU, ATT):
    '''return earth frame gyro vector'''
    ...

def airspeed_energy_error(NAV_CONTROLLER_OUTPUT, VFR_HUD):
    '''return airspeed energy error matching APM internals
    This is positive when we are going too slow
    '''
    ...

def energy_error(NAV_CONTROLLER_OUTPUT, VFR_HUD):
    '''return energy error matching APM internals
    This is positive when we are too low or going too slow
    '''
    ...

def rover_turn_circle(SERVO_OUTPUT_RAW):
    '''return turning circle (diameter) in meters for steering_angle in degrees
    '''
    ...

def rover_yaw_rate(VFR_HUD, SERVO_OUTPUT_RAW):
    '''return yaw rate in degrees/second given steering_angle and speed'''
    ...

def rover_lat_accel(VFR_HUD, SERVO_OUTPUT_RAW):
    '''return lateral acceleration in m/s/s'''
    ...

def demix1(servo1, servo2, gain=...):
    '''de-mix a mixed servo output'''
    ...

def demix2(servo1, servo2, gain=...):
    '''de-mix a mixed servo output'''
    ...

def mixer(servo1, servo2, mixtype=..., gain=...):
    '''mix two servos'''
    ...

def mix1(servo1, servo2, mixtype=..., gain=...):
    '''de-mix a mixed servo output'''
    ...

def mix2(servo1, servo2, mixtype=..., gain=...):
    '''de-mix a mixed servo output'''
    ...

def wrap_180(angle):
    ...

def wrap_360(angle):
    ...

class DCM_State:
    '''DCM state object'''
    def __init__(self, roll, pitch, yaw) -> None:
        ...
    
    def update(self, gyro, accel, mag, GPS):
        ...
    


dcm_state = ...
def DCM_update(IMU, ATT, MAG, GPS):
    '''implement full DCM system'''
    ...

class PX4_State:
    '''PX4 DCM state object'''
    def __init__(self, roll, pitch, yaw, timestamp) -> None:
        ...
    
    def update(self, gyro, accel, timestamp):
        ...
    


px4_state = ...
def PX4_update(IMU, ATT):
    '''implement full DCM using PX4 native SD log data'''
    ...

_downsample_N = ...
def downsample(N):
    '''conditional that is true on every Nth sample'''
    ...

def armed(HEARTBEAT):
    '''return 1 if armed, 0 if not'''
    ...

def rotation_df(ATT):
    '''return the current DCM rotation matrix'''
    ...

def rotation2(AHRS2):
    '''return the current DCM rotation matrix'''
    ...

def earth_accel2(RAW_IMU, ATTITUDE):
    '''return earth frame acceleration vector from AHRS2'''
    ...

def earth_accel_df(IMU, ATT):
    '''return earth frame acceleration vector from df log'''
    ...

def earth_accel2_df(IMU, IMU2, ATT):
    '''return earth frame acceleration vector from df log'''
    ...

def gps_velocity_df(GPS):
    '''return GPS velocity vector'''
    ...

def distance_gps2(GPS, GPS2):
    '''distance between two points'''
    ...

radius_of_earth = ...
def wrap_valid_longitude(lon):
    ''' wrap a longitude value around to always have a value in the range
      [-180, +180) i.e 0 => 0, 1 => 1, -1 => -1, 181 => -179, -181 => 179
  '''
    ...

def gps_newpos(lat, lon, bearing, distance):
    '''extrapolate latitude/longitude given a heading and distance
  thanks to http://www.movable-type.co.uk/scripts/latlong.html
  '''
    ...

def gps_offset(lat, lon, east, north):
    '''return new lat/lon after moving east/north
  by the given number of meters'''
    ...

ekf_origin = ...
def ekf1_pos(EKF1):
    '''calculate EKF position when EKF disabled'''
    ...

def quat_to_euler(q):
    '''
  Get Euler angles from a quaternion
  :param q: quaternion [w, x, y , z]
  :returns: euler angles [roll, pitch, yaw]
  '''
    ...

def euler_to_quat(e):
    '''
  Get quaternion from euler angles
  :param e: euler angles [roll, pitch, yaw]
  :returns: quaternion [w, x, y , z]
  '''
    ...

def rotate_quat(attitude, roll, pitch, yaw):
    '''
  Returns rotated quaternion
  :param attitude: quaternion [w, x, y , z]
  :param roll: rotation in rad
  :param pitch: rotation in rad
  :param yaw: rotation in rad
  :returns: quaternion [w, x, y , z]
  '''
    ...

def qroll(MSG):
    '''return quaternion roll in degrees'''
    ...

def qpitch(MSG):
    '''return quaternion pitch in degrees'''
    ...

def qyaw(MSG):
    '''return quaternion yaw in degrees'''
    ...

def euler_rotated(MSG, roll, pitch, yaw):
    '''return eulers in radians from quaternion for view at given attitude in euler radians'''
    ...

def euler_p90(MSG):
    '''return eulers in radians from quaternion for view at pitch 90'''
    ...

def qroll_p90(MSG):
    '''return quaternion roll in degrees for view at pitch 90'''
    ...

def qpitch_p90(MSG):
    '''return quaternion roll in degrees for view at pitch 90'''
    ...

def qyaw_p90(MSG):
    '''return quaternion roll in degrees for view at pitch 90'''
    ...

def rotation_df(ATT):
    '''return the current DCM rotation matrix'''
    ...

def rotation2(AHRS2):
    '''return the current DCM rotation matrix'''
    ...

def earth_accel2(RAW_IMU, ATTITUDE):
    '''return earth frame acceleration vector from AHRS2'''
    ...

def earth_accel_df(IMU, ATT):
    '''return earth frame acceleration vector from df log'''
    ...

def earth_accel2_df(IMU, IMU2, ATT):
    '''return earth frame acceleration vector from df log'''
    ...

def gps_velocity_df(GPS):
    '''return GPS velocity vector'''
    ...

def armed(HEARTBEAT):
    '''return 1 if armed, 0 if not'''
    ...

def mode(HEARTBEAT):
    '''return flight mode number'''
    ...

SAMPLING_RES = ...
SAMPLING_MIN_LAT = ...
SAMPLING_MAX_LAT = ...
SAMPLING_MIN_LON = ...
SAMPLING_MAX_LON = ...
declination_table = ...
inclination_table = ...
intensity_table = ...
def interpolate_table(table, latitude_deg, longitude_deg):
    '''interpolate inside a table for a given lat/lon in degrees'''
    ...

earth_declination = ...
def get_mag_field_ef(latitude_deg, longitude_deg):
    ...

def expected_earth_field_lat_lon(lat, lon):
    '''return expected magnetic field for a location'''
    ...

def get_lat_lon_status(GPS):
    '''get lat, lon and status from a GPS message'''
    ...

def expected_earth_field(GPS):
    '''return expected magnetic field for a location'''
    ...

def expected_mag(GPS, ATT, roll_adjust=..., pitch_adjust=..., yaw_adjust=...):
    '''return expected magnetic field for a location and attitude'''
    ...

def expected_mag_latlon(lat, lon, ATT, roll_adjust=..., pitch_adjust=..., yaw_adjust=...):
    '''return expected magnetic field for a location and attitude'''
    ...

def mag_yaw(GPS, ATT, MAG):
    '''calculate heading from raw magnetometer'''
    ...

def expected_mag_yaw(GPS, ATT, MAG, roll_adjust=..., pitch_adjust=..., yaw_adjust=...):
    '''return expected magnetic field for a location and attitude'''
    ...

def earth_field_error(GPS, NKF2):
    '''return vector error in earth field estimate'''
    ...

def distance_home_df(GPS, ORGN):
    '''distance from home origin'''
    ...

def airspeed_estimate(GLOBAL_POSITION_INT, WIND):
    '''estimate airspeed'''
    ...

def distance_from(GPS_RAW1, lat, lon):
    '''
    Return the distance from a given location in meters
    Calculated as the great-circle distance using 'haversine’ formula
    (Ref: http://www.movable-type.co.uk/scripts/latlong.html)
    Uses the globally-average earth radius value of 6371km
    '''
    ...

def distance_lat_lon(lat1, lon1, lat2, lon2):
    '''
    Return the distance between two points in metres
    Calculated as the great-circle distance using 'haversine’ formula
    (Ref: http://www.movable-type.co.uk/scripts/latlong.html)
    Uses the globally-average earth radius value of 6371km
    '''
    ...

def constrain(v, minv, maxv):
    ...

def sim_body_rates(SIM):
    '''return body frame rates from simulator attitudes'''
    ...

def reset_state_data():
    '''reset state data, used on log rewind'''
    ...

EleModel = ...
@lru_cache(maxsize=10000)
def terrain_height(lat, lon):
    '''get terrain height'''
    ...

def terrain_margin_lat_lon(lat1, lon1, alt1, lat2, lon2, alt2):
    '''
    return minimum height above terrain on path between two positions (AMSL)
    '''
    ...

def terrain_margin(TERR, lat, lon, antenna_height):
    '''
    return minimum height above terrain on path between two positions (AMSL)
    '''
    ...

def radio_margin(TERR, lat, lon, antenna_height):
    '''
    return how much height we could lose and still have line of sight from an antenna at antenna_height
    above ground at lat/lon
    '''
    ...

def mm_curr(RCOU, BAT, PWM_MIN, PWM_MAX, Mfirst, Mlast):
    '''
    motor model to predict current draw given PWM to VTOL motors
    returned value should be proportional to expected total current draw
    '''
    ...

def RotateMag(MAG, rotation):
    '''rotate a MAG message by rotation enumeration'''
    ...

def feet(meters):
    '''convert value from meters to feet'''
    ...

def knots(mps):
    '''convert value from m/s to knots'''
    ...

