"""
This type stub file was generated by pyright.
"""

from math import *
from .mavextra import *

"""
This type stub file was generated by pyright.
"""
home = ...
if home is not None:
    extra = ...
def evaluate_expression(expression, vars, nocondition=...):
    '''evaluation an expression'''
    ...

