"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import IntEnum
from typing import Dict, Optional, Tuple

"""
This type stub file was generated by pyright.
"""
class FtpError(IntEnum):
    """error codes"""
    Success = ...
    Fail = ...
    FailErrno = ...
    InvalidDataSize = ...
    InvalidSession = ...
    NoSessionsAvailable = ...
    EndOfFile = ...
    UnknownCommand = ...
    FileExists = ...
    FileProtected = ...
    FileNotFound = ...
    NoErrorCodeInPayload = ...
    NoErrorCodeInNack = ...
    NoFilesystemErrorInPayload = ...
    InvalidErrorCode = ...
    PayloadTooLarge = ...
    InvalidOpcode = ...
    InvalidArguments = ...
    PutAlreadyInProgress = ...
    FailToOpenLocalFile = ...
    RemoteReplyTimeout = ...


HDR_Len = ...
MAX_Payload = ...
@dataclass
class DirectoryEntry:
    """Directory entry, either a file or a directory and the size"""
    name: str
    is_dir: bool
    size_b: int
    ...


class WriteQueue:
    """
    Manages a queue of write operations for the MAVFTP class.

    Keeps track of offsets and sizes for pending write operations to ensure orderly processing.
    """
    def __init__(self, ofs: int, size: int) -> None:
        ...
    


class ParamData:
    """
    A class to manage parameter values and defaults for ArduPilot configuration.
    """
    def __init__(self) -> None:
        ...
    
    def add_param(self, name, value, ptype):
        ...
    
    def add_default(self, name, value, ptype):
        ...
    


class MAVFTPSetting:
    """A single MAVFTP setting with a name, type, value and default value."""
    def __init__(self, name, s_type, default) -> None:
        ...
    


class MAVFTPSettings:
    """A collection of MAVFTP settings."""
    def __init__(self, s_vars) -> None:
        ...
    
    def append(self, v):
        ...
    
    def __getattr__(self, name):
        ...
    
    def __setattr__(self, name, value):
        ...
    


class MAVFTPReturn:
    """The result of a MAVFTP operation."""
    def __init__(self, operation_name: str, error_code: int, system_error: int = ..., invalid_error_code: int = ..., invalid_opcode: int = ..., invalid_payload_size: int = ...) -> None:
        ...
    
    def display_message(self):
        ...
    
    @property
    def return_code(self):
        ...
    


class MAVFTP:
    """
    Implements the client-side logic for the MAVLink File Transfer Protocol (FTP) over MAVLink connections.

    Handles file operations such as reading, writing, listing directories, and managing sessions.
    """
    def __init__(self, master, target_system, target_component, settings=...) -> None:
        ...
    
    def cmd_ftp(self, args) -> MAVFTPReturn:
        '''FTP operations'''
        ...
    
    def cmd_list(self, args) -> MAVFTPReturn:
        '''list files'''
        ...
    
    def read_sector(self, path: str, offset: int, size: int) -> Optional[bytes]:
        ...
    
    def read(self, path: str, size: int, offset: int = ...) -> Optional[bytes]:
        """get file"""
        ...
    
    def cmd_get(self, args, callback=..., progress_callback=...) -> MAVFTPReturn:
        '''get file'''
        ...
    
    def cmd_put(self, args, fh=..., callback=..., progress_callback=...) -> MAVFTPReturn:
        '''put file'''
        ...
    
    def cmd_rm(self, args) -> MAVFTPReturn:
        '''remove file'''
        ...
    
    def cmd_rmdir(self, args):
        '''remove directory'''
        ...
    
    def cmd_rename(self, args) -> MAVFTPReturn:
        '''rename file or directory'''
        ...
    
    def cmd_mkdir(self, args) -> MAVFTPReturn:
        '''make directory'''
        ...
    
    def cmd_crc(self, args) -> MAVFTPReturn:
        '''get file crc'''
        ...
    
    def cmd_cancel(self) -> MAVFTPReturn:
        '''cancel any pending op'''
        ...
    
    def cmd_status(self) -> MAVFTPReturn:
        '''show status'''
        ...
    
    def process_ftp_reply(self, operation_name, timeout=...) -> MAVFTPReturn:
        ''' execute an FTP operation that requires processing a MAVLink response'''
        ...
    
    @staticmethod
    def ftp_param_decode(data):
        '''decode parameter data, returning ParamData'''
        ...
    
    @staticmethod
    def missionplanner_sort(item: str) -> Tuple[str, ...]:
        """
        Sorts a parameter name according to the rules defined in the Mission Planner software.
        """
        ...
    
    @staticmethod
    def extract_params(pdata, sort_type) -> Dict[str, Tuple[float, str]]:
        ''' extract parameter values to an optionally sorted dictionary of name->(value, type)'''
        ...
    
    @staticmethod
    def save_params(pdict: Dict[str, Tuple[float, str]], filename: str, sort_type: str, add_datatype_comments: bool, add_timestamp_comment: bool) -> None:
        '''Save Ardupilot parameter information to a local file'''
        ...
    
    def cmd_getparams(self, args, progress_callback=..., sort_type: str = ..., add_datatype_comments: bool = ..., add_timestamp_comment: bool = ...):
        ''' Decode the parameter file and save the values and defaults to disk '''
        ...
    


if __name__ == "__main__":
    def argument_parser():
        """
        Parses command-line arguments for the script.

        This function sets up an argument parser to handle the command-line arguments for the script.
        """
        ...
    
    def auto_detect_serial():
        ...
    
    def auto_connect(device):
        ...
    
    def wait_heartbeat(m):
        '''wait for a heartbeat so we know the target system IDs'''
        ...
    
    def main():
        '''for testing/example purposes only'''
        ...
    
