"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class MAVParmDict(dict):
    def __init__(self, *args) -> None:
        ...
    
    def mavset(self, mav, name, value, retries=..., parm_type=...):
        '''set a parameter on a mavlink connection'''
        ...
    
    def save(self, filename, wildcard=..., verbose=...):
        '''save parameters to a file'''
        ...
    
    def load(self, filename, wildcard=..., mav=..., check=..., use_excludes=...):
        '''load parameters from a file'''
        ...
    
    def show_param_value(self, name, value):
        ...
    
    def show(self, wildcard=...):
        '''show parameters'''
        ...
    
    def diff(self, filename, wildcard=..., use_excludes=..., use_tabs=..., show_only1=..., show_only2=...):
        '''show differences with another parameter file'''
        ...
    


