"""
This type stub file was generated by pyright.
"""

import os

"""
This type stub file was generated by pyright.
"""
UDP_MAX_PACKET_LEN = ...
mavlink = ...
mavfile_global = ...
default_native = ...
global_link_id = ...
if not 'MAVLINK_DIALECT' in os.environ:
    ...
def mavlink10():
    '''return True if using MAVLink 1.0 or later'''
    ...

def mavlink20():
    '''return True if using MAVLink 2.0'''
    ...

def evaluate_expression(expression, vars, nocondition=...):
    '''evaluation an expression'''
    ...

def evaluate_condition(condition, vars):
    '''evaluation a conditional (boolean) statement'''
    ...

def u_ord(c):
    ...

class location:
    '''represent a GPS coordinate'''
    def __init__(self, lat, lng, alt=..., heading=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def add_message(messages, mtype, msg):
    '''add a msg to array of messages, taking account of instance messages'''
    ...

def set_dialect(dialect, with_type_annotations=...):
    '''set the MAVLink dialect to work with.
    For example, set_dialect("ardupilotmega")
    '''
    ...

class mavfile_state:
    '''state for a particular system id'''
    def __init__(self) -> None:
        ...
    


class param_state:
    '''state for a particular system id/component id pair'''
    def __init__(self) -> None:
        ...
    


class mavfile:
    '''a generic mavlink port'''
    def __init__(self, fd, address, source_system=..., source_component=..., notimestamps=..., input=..., use_native=...) -> None:
        ...
    
    @property
    def target_system(self):
        ...
    
    @property
    def target_component(self):
        ...
    
    @target_system.setter
    def target_system(self, value):
        ...
    
    @target_component.setter
    def target_component(self, value):
        ...
    
    @property
    def params(self):
        ...
    
    @property
    def messages(self):
        ...
    
    @property
    def flightmode(self):
        ...
    
    @flightmode.setter
    def flightmode(self, value):
        ...
    
    @property
    def vehicle_type(self):
        ...
    
    @vehicle_type.setter
    def vehicle_type(self, value):
        ...
    
    @property
    def mav_type(self):
        ...
    
    @mav_type.setter
    def mav_type(self, value):
        ...
    
    @property
    def base_mode(self):
        ...
    
    @base_mode.setter
    def base_mode(self, value):
        ...
    
    def auto_mavlink_version(self, buf):
        '''auto-switch mavlink protocol version'''
        ...
    
    def recv(self, n=...):
        '''default recv method'''
        ...
    
    def close(self, n=...):
        '''default close method'''
        ...
    
    def write(self, buf):
        '''default write method'''
        ...
    
    def select(self, timeout):
        '''wait for up to timeout seconds for more data'''
        ...
    
    def pre_message(self):
        '''default pre message call'''
        ...
    
    def set_rtscts(self, enable):
        '''enable/disable RTS/CTS if applicable'''
        ...
    
    def probably_vehicle_heartbeat(self, msg):
        ...
    
    def post_message(self, msg):
        '''default post message call'''
        ...
    
    def packet_loss(self):
        '''packet loss as a percentage'''
        ...
    
    def recv_msg(self):
        '''message receive routine'''
        ...
    
    def recv_match(self, condition=..., type=..., blocking=..., timeout=...):
        '''recv the next MAVLink message that matches the given condition
        type can be a string or a list of strings'''
        ...
    
    def check_condition(self, condition):
        '''check if a condition is true'''
        ...
    
    def mavlink10(self):
        '''return True if using MAVLink 1.0 or later'''
        ...
    
    def mavlink20(self):
        '''return True if using MAVLink 2.0 or later'''
        ...
    
    def setup_logfile(self, logfile, mode=...):
        '''start logging to the given logfile, with timestamps'''
        ...
    
    def setup_logfile_raw(self, logfile, mode=...):
        '''start logging raw bytes to the given logfile, without timestamps'''
        ...
    
    def wait_heartbeat(self, blocking=..., timeout=...):
        '''wait for a heartbeat so we know the target system IDs'''
        ...
    
    def param_fetch_all(self):
        '''initiate fetch of all parameters'''
        ...
    
    def param_fetch_one(self, name):
        '''initiate fetch of one parameter'''
        ...
    
    def time_since(self, mtype):
        '''return the time since the last message of type mtype was received'''
        ...
    
    def param_set_send(self, parm_name, parm_value, parm_type=...):
        '''wrapper for parameter set'''
        ...
    
    def waypoint_request_list_send(self):
        '''wrapper for waypoint_request_list_send'''
        ...
    
    def waypoint_clear_all_send(self):
        '''wrapper for waypoint_clear_all_send'''
        ...
    
    def waypoint_request_send(self, seq):
        '''wrapper for waypoint_request_send'''
        ...
    
    def waypoint_set_current_send(self, seq):
        '''wrapper for waypoint_set_current_send'''
        ...
    
    def waypoint_current(self):
        '''return current waypoint'''
        ...
    
    def waypoint_count_send(self, seq):
        '''wrapper for waypoint_count_send'''
        ...
    
    def set_mode_flag(self, flag, enable):
        '''
        Enables/ disables MAV_MODE_FLAG
        @param flag The mode flag, 
          see MAV_MODE_FLAG enum
        @param enable Enable the flag, (True/False)
        '''
        ...
    
    def set_mode_auto(self):
        '''enter auto mode'''
        ...
    
    def mode_mapping(self):
        '''return dictionary mapping mode names to numbers, or None if unknown'''
        ...
    
    def set_mode_apm(self, mode, custom_mode=..., custom_sub_mode=...):
        '''enter arbitrary mode'''
        ...
    
    def set_mode_px4(self, mode, custom_mode, custom_sub_mode):
        '''enter arbitrary mode'''
        ...
    
    def set_mode(self, mode, custom_mode=..., custom_sub_mode=...):
        '''set arbitrary flight mode'''
        ...
    
    def set_mode_rtl(self):
        '''enter RTL mode'''
        ...
    
    def set_mode_manual(self):
        '''enter MANUAL mode'''
        ...
    
    def set_mode_fbwa(self):
        '''enter FBWA mode'''
        ...
    
    def set_mode_loiter(self):
        '''enter LOITER mode'''
        ...
    
    def set_servo(self, channel, pwm):
        '''set a servo value'''
        ...
    
    def set_relay(self, relay_pin=..., state=...):
        '''Set relay_pin to value of state'''
        ...
    
    def calibrate_level(self):
        '''calibrate accels (1D version)'''
        ...
    
    def calibrate_pressure(self):
        '''calibrate pressure'''
        ...
    
    def reboot_autopilot(self, hold_in_bootloader=..., force=...):
        '''reboot the autopilot'''
        ...
    
    def wait_gps_fix(self):
        ...
    
    def location(self, relative_alt=...):
        '''return current location'''
        ...
    
    def arducopter_arm(self):
        '''arm motors (arducopter only)'''
        ...
    
    def arducopter_disarm(self):
        '''disarm motors (arducopter only)'''
        ...
    
    def motors_armed(self):
        '''return true if motors armed'''
        ...
    
    def motors_armed_wait(self):
        '''wait for motors to be armed'''
        ...
    
    def motors_disarmed_wait(self):
        '''wait for motors to be disarmed'''
        ...
    
    def field(self, type, field, default=...):
        '''convenient function for returning an arbitrary MAVLink
           field with a default'''
        ...
    
    def param(self, name, default=...):
        '''convenient function for returning an arbitrary MAVLink
           parameter with a default'''
        ...
    
    def setup_signing(self, secret_key, sign_outgoing=..., allow_unsigned_callback=..., initial_timestamp=..., link_id=...):
        '''setup for MAVLink2 signing'''
        ...
    
    def disable_signing(self):
        '''disable MAVLink2 signing'''
        ...
    


def set_close_on_exec(fd):
    '''set the close on exec flag on a file descriptor. Ignore exceptions'''
    ...

class FakeSerial:
    def __init__(self) -> None:
        ...
    
    def read(self, len):
        ...
    
    def write(self, buf):
        ...
    
    def inWaiting(self):
        ...
    
    def close(self):
        ...
    


class mavserial(mavfile):
    '''a serial mavlink port'''
    def __init__(self, device, baud=..., autoreconnect=..., source_system=..., source_component=..., use_native=..., force_connected=...) -> None:
        ...
    
    def set_rtscts(self, enable):
        '''enable/disable RTS/CTS if applicable'''
        ...
    
    def set_baudrate(self, baudrate):
        '''set baudrate'''
        ...
    
    def close(self):
        ...
    
    def recv(self, n=...):
        ...
    
    def write(self, buf):
        ...
    
    def reset(self):
        ...
    


class mavudp(mavfile):
    '''a UDP mavlink socket'''
    def __init__(self, device, input=..., broadcast=..., source_system=..., source_component=..., use_native=..., timeout=...) -> None:
        ...
    
    def close(self):
        ...
    
    def recv(self, n=...):
        ...
    
    def write(self, buf):
        ...
    
    def recv_msg(self):
        '''message receive routine for UDP link'''
        ...
    


class mavmcast(mavfile):
    '''a UDP multicast mavlink socket'''
    def __init__(self, device, broadcast=..., source_system=..., source_component=..., use_native=...) -> None:
        ...
    
    def close(self):
        ...
    
    def recv(self, n=...):
        ...
    
    def write(self, buf):
        ...
    
    def recv_msg(self):
        '''message receive routine for UDP link'''
        ...
    


class mavtcp(mavfile):
    '''a TCP mavlink socket'''
    def __init__(self, device, autoreconnect=..., source_system=..., source_component=..., retries=..., use_native=...) -> None:
        ...
    
    def do_connect(self):
        ...
    
    def close(self):
        ...
    
    def handle_disconnect(self):
        ...
    
    def handle_eof(self):
        ...
    
    def recv(self, n=...):
        ...
    
    def write(self, buf):
        ...
    
    def reconnect(self):
        ...
    


class mavtcpin(mavfile):
    '''a TCP input mavlink socket'''
    def __init__(self, device, source_system=..., source_component=..., retries=..., use_native=...) -> None:
        ...
    
    def close(self):
        ...
    
    def recv(self, n=...):
        ...
    
    def write(self, buf):
        ...
    


class mavlogfile(mavfile):
    '''a MAVLink logfile reader/writer'''
    def __init__(self, filename, planner_format=..., write=..., append=..., robust_parsing=..., notimestamps=..., source_system=..., source_component=..., use_native=...) -> None:
        ...
    
    def close(self):
        ...
    
    def recv(self, n=...):
        ...
    
    def write(self, buf):
        ...
    
    def scan_timestamp(self, tbuf):
        '''scan forward looking in a tlog for a timestamp in a reasonable range'''
        ...
    
    def pre_message(self):
        '''read timestamp if needed'''
        ...
    
    def post_message(self, msg):
        '''add timestamp to message'''
        ...
    


class mavmmaplog(mavlogfile):
    '''a MAVLink log file accessed via mmap. Used for fast read-only
    access with low memory overhead where particular message types are wanted'''
    def __init__(self, filename, progress_callback=...) -> None:
        ...
    
    def rewind(self):
        '''rewind to start of log'''
        ...
    
    def close(self):
        ...
    
    def init_arrays(self, progress_callback=...):
        '''initialise arrays for fast recv_match()'''
        ...
    
    def skip_to_type(self, type):
        '''skip fwd to next msg matching given type set'''
        ...
    
    def recv_match(self, condition=..., type=..., blocking=..., timeout=...):
        '''recv the next message that matches the given condition
        type can be a string or a list of strings'''
        ...
    
    def flightmode_list(self):
        '''return an array of tuples for all flightmodes in log. Tuple is (modestring, t0, t1)'''
        ...
    


class mavchildexec(mavfile):
    '''a MAVLink child processes reader/writer'''
    def __init__(self, filename, source_system=..., source_component=..., use_native=...) -> None:
        ...
    
    def close(self):
        ...
    
    def recv(self, n=...):
        ...
    
    def write(self, buf):
        ...
    


class mavwebsocket(mavfile):
    '''Mavlink WebSocket server, single client only'''
    def __init__(self, device, source_system=..., source_component=..., use_native=...) -> None:
        ...
    
    def close_port(self):
        ...
    
    def close(self):
        ...
    
    def recv(self, n=...):
        ...
    
    def write(self, buf):
        ...
    


class mavwebsocket_client(mavfile):
    '''client using WebSocket over TCP with WS and WSS support'''
    def __init__(self, device, source_system=..., source_component=..., retries=..., use_native=...) -> None:
        ...
    
    def connect(self):
        ...
    
    def recv(self, n=...):
        ...
    
    def write(self, data):
        ...
    
    def close(self):
        ...
    


def mavlink_connection(device, baud=..., source_system=..., source_component=..., planner_format=..., write=..., append=..., robust_parsing=..., notimestamps=..., input=..., dialect=..., autoreconnect=..., zero_time_base=..., retries=..., use_native=..., force_connected=..., progress_callback=..., udp_timeout=..., **opts):
    '''open a serial, UDP, TCP or file mavlink connection'''
    ...

class periodic_event:
    '''a class for fixed frequency events'''
    def __init__(self, frequency) -> None:
        ...
    
    def force(self):
        '''force immediate triggering'''
        ...
    
    def trigger(self):
        '''return True if we should trigger now'''
        ...
    


have_ascii = ...
def is_printable(c):
    '''see if a character is printable'''
    ...

def all_printable(buf):
    '''see if a string is all printable'''
    ...

class SerialPort:
    '''auto-detected serial port'''
    def __init__(self, device, description=..., hwid=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def auto_detect_serial_win32(preferred_list=...):
    '''try to auto-detect serial ports on win32'''
    ...

def auto_detect_serial_unix(preferred_list=...):
    '''try to auto-detect serial ports on unix'''
    ...

def auto_detect_serial(preferred_list=...):
    '''try to auto-detect serial port'''
    ...

def mode_string_v09(msg):
    '''mode string for 0.9 protocol'''
    ...

mode_mapping_apm = ...
mode_mapping_acm = ...
mode_mapping_rover = ...
mode_mapping_tracker = ...
mode_mapping_sub = ...
mode_mapping_blimp = ...
AP_MAV_TYPE_MODE_MAP_DEFAULT = ...
_custom_mode_map_path = ...
_custom_mode_map_path = ...
_custom_mode_map = ...
AP_MAV_TYPE_MODE_MAP = ...
mainstate_mapping_px4 = ...
def mode_string_px4(MainState):
    ...

PX4_CUSTOM_MAIN_MODE_MANUAL = ...
PX4_CUSTOM_MAIN_MODE_ALTCTL = ...
PX4_CUSTOM_MAIN_MODE_POSCTL = ...
PX4_CUSTOM_MAIN_MODE_AUTO = ...
PX4_CUSTOM_MAIN_MODE_ACRO = ...
PX4_CUSTOM_MAIN_MODE_OFFBOARD = ...
PX4_CUSTOM_MAIN_MODE_STABILIZED = ...
PX4_CUSTOM_MAIN_MODE_RATTITUDE = ...
PX4_CUSTOM_SUB_MODE_OFFBOARD = ...
PX4_CUSTOM_SUB_MODE_AUTO_READY = ...
PX4_CUSTOM_SUB_MODE_AUTO_TAKEOFF = ...
PX4_CUSTOM_SUB_MODE_AUTO_LOITER = ...
PX4_CUSTOM_SUB_MODE_AUTO_MISSION = ...
PX4_CUSTOM_SUB_MODE_AUTO_RTL = ...
PX4_CUSTOM_SUB_MODE_AUTO_LAND = ...
PX4_CUSTOM_SUB_MODE_AUTO_RTGS = ...
PX4_CUSTOM_SUB_MODE_AUTO_FOLLOW_TARGET = ...
auto_mode_flags = ...
px4_map = ...
def interpret_px4_mode(base_mode, custom_mode):
    ...

def mode_mapping_byname(mav_type):
    '''return dictionary mapping mode names to numbers, or None if unknown'''
    ...

def mode_mapping_bynumber(mav_type):
    '''return dictionary mapping mode numbers to name, or None if unknown'''
    ...

def mode_string_v10(msg):
    '''mode string for 1.0 protocol, from heartbeat'''
    ...

def mode_string_apm(mode_number):
    '''return mode string for ArduPlane'''
    ...

def mode_string_acm(mode_number):
    '''return mode string for ArduCopter'''
    ...

class MavlinkSerialPort:
    '''an object that looks like a serial port, but
        transmits using mavlink SERIAL_CONTROL packets'''
    def __init__(self, portname, baudrate, devnum=..., devbaud=..., timeout=..., debug=...) -> None:
        ...
    
    def debug(self, s, level=...):
        '''write some debug text'''
        ...
    
    def write(self, b):
        '''write some bytes'''
        ...
    
    def read(self, n):
        '''read some bytes'''
        ...
    
    def flushInput(self):
        '''flush any pending input'''
        ...
    
    def setBaudrate(self, baudrate):
        '''set baudrate'''
        ...
    


def decode_bitmask(messagetype, field, value):
    class EnumBitInfo:
        ...
    
    

dump_message_unit_decoder = ...
def dump_message_verbose(f, m):
    '''write an excruciatingly detailed dump of message m to file descriptor f'''
    ...

if __name__ == '__main__':
    serial_list = ...
