"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
HAVE_PROTOBUF = ...
class MAVWPError(Exception):
    '''MAVLink WP error class'''
    def __init__(self, msg) -> None:
        ...
    


class MissionItemProtocol:
    '''Base class for transferring items based on the MISSION_ITEM protocol'''
    def __init__(self, target_system=..., target_component=...) -> None:
        ...
    
    def count(self):
        '''return number of waypoints'''
        ...
    
    def wp(self, i):
        '''alias for backwards compatability'''
        ...
    
    def item(self, i):
        '''return an item'''
        ...
    
    def add(self, w, comment=...):
        '''add a waypoint'''
        ...
    
    def insert(self, idx, w, comment=...):
        '''insert a waypoint'''
        ...
    
    def reindex(self):
        '''reindex waypoints'''
        ...
    
    def set(self, w, idx):
        '''set a waypoint'''
        ...
    
    def remove(self, w):
        '''remove a waypoint'''
        ...
    
    def clear(self):
        '''clear waypoint list'''
        ...
    
    def load(self, filename):
        '''load waypoints from a file.
        returns number of waypoints loaded'''
        ...
    
    def save_as_pb(self, filename):
        ...
    
    def save(self, filename):
        '''save waypoints to a file'''
        ...
    
    def view_indexes(self, done=...):
        '''return a list waypoint indexes in view order'''
        ...
    
    def polygon(self, done=...):
        '''return a polygon for the waypoints'''
        ...
    
    def polygon_list(self):
        '''return a list of polygons for the waypoints'''
        ...
    
    def view_list(self):
        '''return a list of polygon indexes lists for the waypoints'''
        ...
    


class MAVWPLoader(MissionItemProtocol):
    '''MAVLink waypoint loader'''
    def mav_mission_type(self):
        '''returns type of mission this object transfers'''
        ...
    
    def wp_is_loiter(self, i):
        '''return true if waypoint is a loiter waypoint'''
        ...
    
    def add_latlonalt(self, lat, lon, altitude, terrain_alt=...):
        '''add a point via latitude/longitude/altitude'''
        ...
    
    def is_location_command(self, cmd):
        '''see if cmd is a MAV_CMD with a latitude/longitude'''
        ...
    
    def is_location_wp(self, w):
        '''see if w.command is a MAV_CMD with a latitude/longitude'''
        ...
    


def get_first_line_from_file(filename):
    '''return line from filename that doesn't start with a #'''
    ...

class MissionItemProtocol_Fence(MissionItemProtocol):
    '''New mission-item-protocol-based class for sending fence points to
    autopilot'''
    def mav_mission_type(self):
        '''returns type of mission this object transfers'''
        ...
    
    def is_location_command(self, cmd):
        '''returns true if cmd nominates a location in param5/param6/param7'''
        ...
    
    def load(self, filename):
        '''try to load from an old "FENCE_POINT" format file (just a list of
        latlon pairs - or fall back to QGC formats'''
        ...
    


class MissionItemProtocol_Rally(MissionItemProtocol):
    '''New mission-item-protocol-based class for sending rally points to
    autopilot'''
    def mav_mission_type(self):
        '''returns type of mission this object transfers'''
        ...
    
    def is_location_command(self, cmd):
        '''returns true if cmd nominates a location in param5/param6/param7'''
        ...
    
    def load(self, filename):
        '''attempts to load from legacy rally file'''
        ...
    


class MAVRallyError(Exception):
    '''MAVLink rally point error class'''
    def __init__(self, msg) -> None:
        ...
    


class MAVRallyLoader:
    '''MAVLink Rally points and Rally Land points loader'''
    def __init__(self, target_system=..., target_component=...) -> None:
        ...
    
    def rally_count(self):
        '''return number of rally points'''
        ...
    
    def rally_point(self, i):
        '''return rally point i'''
        ...
    
    def reindex(self):
        '''reset counters and indexes'''
        ...
    
    def append_rally_point(self, p):
        '''add rallypoint to end of list'''
        ...
    
    def create_and_append_rally_point(self, lat, lon, alt, break_alt, land_dir, flags):
        '''add a point via latitude/longitude'''
        ...
    
    def clear(self):
        '''clear all point lists (rally and rally_land)'''
        ...
    
    def remove(self, i):
        '''remove a rally point'''
        ...
    
    def move(self, i, lat, lng, change_time=...):
        '''move a rally point'''
        ...
    
    def set_alt(self, i, alt, break_alt=..., change_time=...):
        '''set rally point altitude(s)'''
        ...
    
    def load(self, filename):
        '''load rally and rally_land points from a file.
         returns number of points loaded'''
        ...
    
    def save(self, filename):
        '''save fence points to a file'''
        ...
    


class MAVFenceError(Exception):
    '''MAVLink fence error class'''
    def __init__(self, msg) -> None:
        ...
    


class MAVFenceLoader:
    '''MAVLink geo-fence loader'''
    def __init__(self, target_system=..., target_component=...) -> None:
        ...
    
    def count(self):
        '''return number of points'''
        ...
    
    def point(self, i):
        '''return a point'''
        ...
    
    def add(self, p):
        '''add a point'''
        ...
    
    def reindex(self):
        '''reindex waypoints'''
        ...
    
    def add_latlon(self, lat, lon):
        '''add a point via latitude/longitude'''
        ...
    
    def clear(self):
        '''clear point list'''
        ...
    
    def load(self, filename):
        '''load points from a file.
        returns number of points loaded'''
        ...
    
    def save(self, filename):
        '''save fence points to a file'''
        ...
    
    def move(self, i, lat, lng, change_time=...):
        '''move a fence point'''
        ...
    
    def remove(self, i, change_time=...):
        '''remove a fence point'''
        ...
    
    def polygon(self):
        '''return a polygon for the fence'''
        ...
    


