"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class Vector3:
    '''a vector'''
    def __init__(self, x=..., y=..., z=...) -> None:
        ...
    
    def __repr__(self):
        ...
    
    def __eq__(self, v) -> bool:
        ...
    
    def __ne__(self, v) -> bool:
        ...
    
    def close(self, v, tol=...):
        ...
    
    def __add__(self, v):
        ...
    
    __radd__ = ...
    def __sub__(self, v):
        ...
    
    def __neg__(self):
        ...
    
    def __rsub__(self, v):
        ...
    
    def __mul__(self, v):
        ...
    
    __rmul__ = ...
    def __div__(self, v):
        ...
    
    def __truediv__(self, v):
        ...
    
    def __floordiv__(self, v):
        ...
    
    def __mod__(self, v):
        '''cross product'''
        ...
    
    def __copy__(self):
        ...
    
    copy = ...
    def length(self):
        ...
    
    def zero(self):
        ...
    
    def angle(self, v):
        '''return the angle between this vector and another vector'''
        ...
    
    def normalized(self):
        ...
    
    def normalize(self):
        ...
    
    def rotate_by_id(self, rot_id):
        '''rotate a vector using a rotation enum ID'''
        ...
    
    def rotate_by_inverse_id(self, rot_id):
        '''rotate a vector using a inverse rotation enum ID'''
        ...
    


class Matrix3:
    '''a 3x3 matrix, intended as a rotation matrix'''
    def __init__(self, a=..., b=..., c=...) -> None:
        ...
    
    def __repr__(self):
        ...
    
    def identity(self):
        ...
    
    def transposed(self):
        ...
    
    def from_euler(self, roll, pitch, yaw):
        '''fill the matrix from Euler angles in radians'''
        ...
    
    def to_euler(self):
        '''find Euler angles (321 convention) for the matrix'''
        ...
    
    def to_euler312(self):
        '''find Euler angles (312 convention) for the matrix.
        See http://www.atacolorado.com/eulersequences.doc
        '''
        ...
    
    def from_euler312(self, roll, pitch, yaw):
        '''fill the matrix from Euler angles in radians in 312 convention'''
        ...
    
    def determinant(self):
        '''return determinant'''
        ...
    
    def invert(self):
        '''invert 3x3 matrix, returning new matrix'''
        ...
    
    def __add__(self, m):
        ...
    
    __radd__ = ...
    def __sub__(self, m):
        ...
    
    def __rsub__(self, m):
        ...
    
    def __eq__(self, m) -> bool:
        ...
    
    def __ne__(self, m) -> bool:
        ...
    
    def __mul__(self, other):
        ...
    
    def __div__(self, v):
        ...
    
    def __truediv__(self, v):
        ...
    
    def __neg__(self):
        ...
    
    def __copy__(self):
        ...
    
    copy = ...
    def rotate(self, g):
        '''rotate the matrix by a given amount on 3 axes,
        where g is a vector of delta angles. Used
        with DCM updates in mavextra.py'''
        ...
    
    def rotate_yaw(self, yrad):
        '''rotate the matrix by a given amount in-place on yaw axis'''
        ...
    
    def rotate_pitch(self, prad):
        '''rotate the matrix by a given amount in-place on pitch axis'''
        ...
    
    def rotate_roll(self, rrad):
        '''rotate the matrix by a given amount in-place on roll axis'''
        ...
    
    def rotate_321(self, ryad, prad, yrad):
        '''rotate the matrix by a given amount in-place on 3 axes with 321 ordering'''
        ...
    
    def rotate_312(self, ryad, prad, yrad):
        '''rotate the matrix by a given amount in-place on 3 axes with 312 ordering'''
        ...
    
    def normalize(self):
        '''re-normalise a rotation matrix'''
        ...
    
    def trace(self):
        '''the trace of the matrix'''
        ...
    
    def from_axis_angle(self, axis, angle):
        '''create a rotation matrix from axis and angle'''
        ...
    
    def from_two_vectors(self, vec1, vec2):
        '''get a rotation matrix from two vectors.
           This returns a rotation matrix which when applied to vec1
           will produce a vector pointing in the same direction as vec2'''
        ...
    
    def close(self, m, tol=...):
        ...
    


class Plane:
    '''a plane in 3 space, defined by a point and a vector normal'''
    def __init__(self, point=..., normal=...) -> None:
        ...
    


class Line:
    '''a line in 3 space, defined by a point and a vector'''
    def __init__(self, point=..., vector=...) -> None:
        ...
    
    def plane_intersection(self, plane, forward_only=...):
        '''return point where line intersects with a plane'''
        ...
    


class Rotation:
    def __init__(self, name, roll, pitch, yaw) -> None:
        ...
    


rotations = ...
