"""
This type stub file was generated by pyright.
"""

'''
MAVLink CRC-16/MCRF4XX code

Copyright Andrew Tridgell
Released under GNU LGPL version 3 or later
'''
mcrf4xx = ...
class x25crc_slow:
    """CRC-16/MCRF4XX - based on checksum.h from mavlink library"""
    def __init__(self, buf=...) -> None:
        ...
    
    def accumulate(self, buf): # -> None:
        """add in some more bytes (it also accepts strings)"""
        ...
    
    def accumulate_str(self, buf): # -> None:
        """
        Provided for backwards compatibility. accumulate now also works on strings.
        """
        ...
    


class x25crc_fast:
    """CRC-16/MCRF4XX - based on checksum.h from mavlink library"""
    def __init__(self, buf=...) -> None:
        ...
    
    def accumulate(self, buf): # -> None:
        """add in some more bytes (it also accepts strings)"""
        ...
    
    def accumulate_str(self, buf): # -> None:
        """
        Provided for backwards compatibility. accumulate now also works on strings.
        """
        ...
    


if mcrf4xx is not None:
    x25crc = ...
else:
    x25crc = ...
if __name__ == "__main__":
    ...
