"""
This type stub file was generated by pyright.
"""

'''parse a MAVLink protocol XML file and generate a python implementation

Copyright Andrew Tridgell 2011
Released under GNU GPL version 3 or later

General process:
 - each filename passed in:
    - may be validated, based on --validate
    - is parsed using mavparse.MAVXML into an xml document and appended to a list, "xml"

 - expand_includes is called to do a breadth-first search of the xml
    documents structure inferred by the <include> tags in each
    document, expanding the xml list from its base (just the ones on
    the commandline) to the entire structure

 - update_includes works on the xml list created by expand_includes
    - any xml document with no includes is added to the "done" list (there must be at least one of these)
    - it repeatedly calls update_one_iteration
    - each iteration is intended to include the crcs and other information from includes into the xml document doing the include

'''
schemaFile = ...
DEFAULT_WIRE_PROTOCOL = ...
DEFAULT_LANGUAGE = ...
DEFAULT_VALIDATE = ...
DEFAULT_STRICT_UNITS = ...
MAXIMUM_INCLUDE_FILE_NESTING = ...
supportedLanguages = ...
def mavgen(opts, args):
    """Generate mavlink message formatters and parsers (C and Python ) using options
    and args where args are a list of xml files. This function allows python
    scripts under Windows to control mavgen using the same interface as
    shell scripts under Unix"""
    ...

class Opts:
    def __init__(self, output, wire_protocol=..., language=..., validate=..., strict_units=...) -> None:
        ...
    


def mavgen_python_dialect(dialect, wire_protocol): # -> bool:
    '''generate the python code on the fly for a MAVLink dialect'''
    ...

if __name__ == "__main__":
    ...
