"""
This type stub file was generated by pyright.
"""

"""
Parse a MAVLink protocol XML file and generate Swift implementation

Copyright Max Odnovolyk 2015
Released under GNU GPL version 3 or later
"""
abbreviations = ...
swift_keywords = ...
swift_types = ...
t = ...
def generate_mavlink(directory, filelist, xml_list, msgs): # -> None:
    ...

def generate_header(outf, filelist, xml_list, filename): # -> None:
    """Generate Swift file header with source files list and creation date"""
    ...

def generate_enums(directory, filelist, xml_list, enums): # -> None:
    """Iterate through all enums and create Swift equivalents"""
    ...

def generate_optionsets(directory, filelist, xml_list, enums): # -> None:
    """Iterate through all enums and create Swift equivalents"""
    ...

def get_enum_raw_type(enum, msgs): # -> Literal['Int']:
    """Search appropriate raw type for enums in messages fields"""
    ...

def generate_messages(directory, filelist, xml_list, msgs): # -> None:
    """Generate Swift structs to represent all MAVLink messages"""
    ...

def append_static_code(filename, outf): # -> None:
    """Open and copy static code from specified file"""
    ...

def generate_message_mappings_array(outf, msgs): # -> None:
    """Create array for mapping message Ids to proper structs"""
    ...

def generate_message_lengths_array(outf, msgs): # -> None:
    """Create array with message lengths to validate known message lengths"""
    ...

def generate_message_crc_extra_array(outf, msgs): # -> None:
    """Add array with CRC extra values to detect incompatible XML changes"""
    ...

def camel_case_from_underscores(string): # -> Literal['']:
    """Generate a CamelCase string from an underscore_string"""
    ...

def lower_camel_case_from_underscores(string):
    """Generate a lower-cased camelCase string from an underscore_string"""
    ...

def contains_a_bitmask(enums, enumName): # -> Literal[False]:
    ...

def enum_is_a_bitmask(enum): # -> bool:
    ...

def generate_enums_type_info(enums, msgs): # -> None:
    """Add camel case swift names for enums an entries, descriptions and sort enums alphabetically"""
    ...

def generate_messages_type_info(msgs, enums): # -> None:
    """Add proper formatted variable names, initializers and type names to use in templates"""
    ...

def generate(basename, xml_list): # -> None:
    """Generate complete MAVLink Swift implementation"""
    ...

