"""
This type stub file was generated by pyright.
"""

'''
parse a MAVLink protocol XML file and generate a Wireshark Lua dissector

Example usage on Linux or macOS:

# assuming you have cloned the mavlink repo to /mavlink
MXML="/mavlink/message_definitions/v1.0/ardupilotmega.xml"
# Wireshark -> About Wireshark -> Folders -> Personal Lua Plugins
WIRESHARK_PLUGINS="~/.local/lib/wireshark/plugins"
mkdir -p $WIRESHARK_PLUGINS
mavgen.py --lang=WLua $MXML -o $WIRESHARK_PLUGINS/mavlink.lua

After doing this, Wireshark should be able to show details of MAVLink packets.

---

Copyright Holger Steinhaus 2012
Released under GNU GPL version 3 or later
'''
t = ...
def get_field_info(field): # -> tuple[Any | Literal['char'], Any | Literal['ftypes.DOUBLE', 'ftypes.STRING'], Any | Literal['string', 'le_uint64', 'le_uint', 'le_int64', 'le_int'], Any | Literal[1], Any | Literal[1]]:
    ...

def generate_preamble(outf): # -> None:
    ...

def generate_body_fields(outf): # -> None:
    ...

def generate_msg_table(outf, msgs): # -> None:
    ...

def is_power_of_2(n): # -> bool:
    ...

def generate_enum_table(outf, enums): # -> None:
    ...

def generate_field_or_param(outf, field_or_param, name, label, physical_type, field_type, enums): # -> None:
    ...

def generate_msg_fields(outf, msg, enums): # -> None:
    ...

def generate_cmd_params(outf, cmd, enums): # -> None:
    ...

def generate_flag_enum_dissector(outf, enum): # -> None:
    ...

def generate_ftp_payload_dissector(outf, msg, field, offset): # -> None:
    ...

custom_field_dissector = ...
unit_decoder_mapping = ...
def generate_field_dissector(outf, msg, field, offset, enums, cmd=..., param=...): # -> None:
    ...

def generate_payload_dissector(outf, msg, cmds, enums, cmd=...): # -> None:
    ...

def generate_packet_dis(outf): # -> None:
    ...

def generate_epilog(outf): # -> None:
    ...

def generate(basename, xml): # -> None:
    '''generate complete lua implemenation'''
    ...

