"""
This type stub file was generated by pyright.
"""

'''
parse a MAVLink protocol XML file and generate a C++ implementation

Based on C implementation and require C-library for framing.

Copyright Andrew Tridgell 2011
Copyright Vladimir Ermakov 2016
Released under GNU GPL version 3 or later
'''
t = ...
def tmax(bit):
    ...

TYPE_MAX = ...
MACROS = ...
EType = ...
def generate_main_hpp(directory, xml): # -> None:
    '''generate main header per XML file'''
    ...

def generate_message_hpp(directory, m): # -> None:
    '''generate per-message header for a XML file'''
    ...

def generate_gtestsuite_hpp(directory, xml): # -> None:
    '''generate gtestsuite.hpp per XML file'''
    ...

def copy_fixed_headers(directory, xml): # -> None:
    '''copy the fixed protocol headers to the target directory'''
    ...

class mav_include:
    def __init__(self, base) -> None:
        ...
    


def enum_remove_prefix(prefix, s): # -> str:
    '''remove prefix from enum entry'''
    ...

def fix_int8_t(v): # -> int:
    '''convert unsigned char value to signed char'''
    ...

def generate_one(basename, xml): # -> None:
    '''generate headers for one XML file'''
    ...

def generate(basename, xml_list): # -> None:
    '''generate serialization MAVLink C++ implemenation'''
    ...

