"""
This type stub file was generated by pyright.
"""

"""
parse a MAVLink protocol XML file and generate a Node.js typescript module implementation

Based on original work Copyright Andrew Tridgell 2011
Released under GNU GPL version 3 or later
"""
t = ...
def camelcase(str): # -> Literal['']:
    ...

def generate_enums(dir, enums): # -> None:
    ...

def generate_classes(dir, registry, msgs, xml): # -> None:
    ...

def generate_tsconfig(basename): # -> None:
    ...

def generate(basename, xml): # -> None:
    ...

