"""
This type stub file was generated by pyright.
"""

'''
parse a MAVLink protocol XML file and generate a Ardupilot LUA mavlink module
'''
def generate(basename, xml): # -> None:
    '''generate complete python implemenation'''
    ...

