"""
This type stub file was generated by pyright.
"""

"""
parse a MAVLink protocol XML file and generate a python implementation

Copyright Andrew Tridgell 2011
Released under GNU GPL version 3 or later
"""
t = ...
def generate_preamble(outf, msgs, basename, args, xml): # -> None:
    ...

def generate_enums(outf, enums): # -> None:
    ...

def generate_message_ids(outf, msgs): # -> None:
    ...

def byname_hash_from_field_attribute(m, attribute): # -> LiteralString:
    ...

def generate_classes(outf, msgs, enums): # -> None:
    ...

def native_mavfmt(field): # -> str:
    """Work out the struct format for a type."""
    ...

def mavfmt(field): # -> str:
    """work out the struct format for a type"""
    ...

def mavpytype(field): # -> str:
    ...

def mavdefault(field): # -> str:
    """returns default value for field (as string) for mavlink2 extensions"""
    ...

def generate_mavlink_class(outf, msgs, xml): # -> None:
    ...

def generate_methods(outf, msgs): # -> None:
    ...

def generate(basename, xml): # -> None:
    """generate complete python implementation"""
    ...

