"""
This type stub file was generated by pyright.
"""

'''
parse a MAVLink protocol XML file and generate a C# implementation

Copyright Michael Oborne 2018
Released under GNU GPL version 3 or later
'''
t = ...
enumtypes = ...
map = ...
def generate_message_header(f, xml_list): # -> None:
    ...

def generate_message_enum_types(xml): # -> None:
    ...

def cleanText(text):
    ...

def generate_message_enums(f, xml): # -> None:
    ...

def generate_message_footer(f, xml): # -> None:
    ...

def generate_message_h(f, directory, m): # -> None:
    '''generate per-message header for a XML file'''
    ...

class mav_include:
    def __init__(self, base) -> None:
        ...
    


def generate_one(fh, basename, xml): # -> None:
    '''generate headers for one XML file'''
    ...

def copy_fixed_headers(directory, xml): # -> None:
    '''copy the fixed protocol headers to the target directory'''
    ...

def generate(basename, xml_list): # -> None:
    '''generate complete MAVLink CSharp implemenation'''
    ...

