"""
This type stub file was generated by pyright.
"""

'''
parse a MAVLink protocol XML file and generate a Node.js javascript module implementation

Based on original work Copyright Andrew Tridgell 2011
Released under GNU GPL version 3 or later
'''
t = ...
def get_mavhead(xml): # -> Literal['mavlink20', 'mavlink10']:
    ...

def get_mavprocessor(xml): # -> Literal['MAVLink20Processor', 'MAVLink10Processor']:
    ...

def generate_preamble(outf, msgs, args, xml): # -> None:
    ...

def generate_enums(outf, enums, xml): # -> None:
    ...

def generate_message_ids(outf, msgs, xml): # -> None:
    ...

def generate_classes(outf, msgs, xml): # -> None:
    """
    Generate the implementations of the classes representing MAVLink messages.

    """
    ...

def mavfmt(field): # -> str:
    '''work out the struct format for a type'''
    ...

def generate_mavlink_class(outf, msgs, xml): # -> None:
    ...

def generate_footer(outf, xml): # -> None:
    ...

def isfloat(value): # -> bool:
    ...

def generate_tests_preamble(outf, msgs, args, xml): # -> None:
    ...

def generate_tests_mavlink_class(outf, msgs, xml): # -> None:
    ...

def generate_tests_footer(outf, xml): # -> None:
    ...

def generate(basename, xml): # -> None:
    '''generate complete javascript implementation'''
    ...

