"""
This type stub file was generated by pyright.
"""

'''
Parse a MAVLink protocol XML file and generate a Java implementation

Copyright Andrew Tridgell 2011
Released under GNU GPL version 3 or later
'''
t = ...
def generate_enums(basename, xml): # -> None:
    '''generate main header per XML file'''
    ...

def generate_CRC(directory, xml): # -> None:
    '''generate CRC definition and crc array per dialect'''
    ...

def generate_message_h(directory, m): # -> None:
    '''generate per-message header for a XML file'''
    ...

def generate_MAVLinkMessage(directory, xml_list): # -> None:
    ...

def copy_fixed_headers(directory, xml): # -> None:
    '''copy the fixed protocol headers to the target directory'''
    ...

class mav_include:
    def __init__(self, base) -> None:
        ...
    


def mavfmt(field, typeInfo=...): # -> str:
    '''work out the struct format for a type'''
    ...

def generate_one(basename, xml): # -> None:
    '''generate headers for one XML file'''
    ...

def removeBrackets(text):
    ...

def cleanText(text):
    ...

def generate(basename, xml_list): # -> None:
    '''generate complete MAVLink Java implemenation'''
    ...

