"""
This type stub file was generated by pyright.
"""

'''
parse a MAVLink protocol XML file and generate an Objective-C implementation

Copyright John Boiles 2013
Released under GNU GPL version 3 or later
'''
t = ...
def generate_mavlink(directory, xml): # -> None:
    '''generate MVMavlink header and implementation'''
    ...

def generate_base_message(directory, xml): # -> None:
    '''Generate base MVMessage header and implementation'''
    ...

def generate_message_definitions_h(directory, xml): # -> None:
    '''generate headerfile containing includes for all messages'''
    ...

def generate_message(directory, m): # -> None:
    '''generate per-message header and implementation file'''
    ...

def camel_case_from_underscores(string): # -> Literal['']:
    """generate a CamelCase string from an underscore_string."""
    ...

def lower_camel_case_from_underscores(string):
    """generate a lower-cased camelCase string from an underscore_string.
    For example: my_variable_name -> myVariableName"""
    ...

def generate_shared(basename, xml_list): # -> None:
    ...

def generate_message_definitions(basename, xml): # -> None:
    '''generate files for one XML file'''
    ...

def generate(basename, xml_list): # -> None:
    '''generate complete MAVLink Objective-C implemenation'''
    ...

