"""
This type stub file was generated by pyright.
"""

'''
parse a MAVLink protocol XML file and generate a C implementation

Copyright Andrew Tridgell 2011
Released under GNU GPL version 3 or later
'''
t = ...
def generate_version_h(directory, xml): # -> None:
    '''generate version.h'''
    ...

def generate_mavlink_h(directory, xml): # -> None:
    '''generate mavlink.h'''
    ...

def generate_main_h(directory, xml): # -> None:
    '''generate main header per XML file'''
    ...

def generate_message_h(directory, m): # -> None:
    '''generate per-message header for a XML file'''
    ...

def generate_testsuite_h(directory, xml): # -> None:
    '''generate testsuite.h per XML file'''
    ...

def copy_fixed_headers(directory, xml): # -> None:
    '''copy the fixed protocol headers to the target directory'''
    ...

class mav_include:
    def __init__(self, base) -> None:
        ...
    


def generate_one(basename, xml): # -> None:
    '''generate headers for one XML file'''
    ...

def generate(basename, xml_list): # -> None:
    '''generate complete MAVLink C implemenation'''
    ...

