"""
This type stub file was generated by pyright.
"""

'''
mavlink python parse functions

Copyright Andrew Tridgell 2011
Released under GNU GPL version 3 or later
'''
PROTOCOL_0_9 = ...
PROTOCOL_1_0 = ...
PROTOCOL_2_0 = ...
FLAG_HAVE_TARGET_SYSTEM = ...
FLAG_HAVE_TARGET_COMPONENT = ...
class MAVParseError(Exception):
    def __init__(self, message, inner_exception=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class MAVField:
    def __init__(self, name, type, print_format, xml, description=..., enum=..., display=..., units=..., multiplier=..., instance=...) -> None:
        ...
    
    def gen_test_value(self, i): # -> str:
        '''generate a testsuite value for a MAVField'''
        ...
    
    def set_test_value(self): # -> None:
        '''set a testsuite value for a MAVField'''
        ...
    


class MAVType:
    def __init__(self, name, id, linenumber, description=...) -> None:
        ...
    
    def base_fields(self): # -> int:
        '''return number of non-extended fields'''
        ...
    


class MAVEnumParam:
    def __init__(self, index, description=..., label=..., units=..., enum=..., increment=..., minValue=..., maxValue=..., reserved=..., default=..., multiplier=...) -> None:
        ...
    
    def set_description(self, description): # -> None:
        ...
    


class MAVEnumEntry:
    def __init__(self, name, value, description=..., end_marker=..., autovalue=..., origin_file=..., origin_line=..., has_location=...) -> None:
        ...
    


class MAVEnum:
    def __init__(self, name, linenumber, description=..., bitmask=...) -> None:
        ...
    


class MAVXML:
    '''parse a mavlink XML file'''
    def __init__(self, filename, wire_protocol_version=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def message_checksum(msg): # -> int:
    '''calculate CRC-16/MCRF4XX checksum of the key fields of a message, so we
       can detect incompatible XML changes'''
    ...

def merge_enums(xml): # -> None:
    '''merge enums between XML files'''
    ...

def check_duplicates(xml): # -> bool:
    '''check for duplicate message IDs'''
    ...

def check_missing_enum(xml): # -> bool:
    '''check for enum fields pointing to invalid enums'''
    ...

def total_msgs(xml): # -> int:
    '''count total number of msgs'''
    ...

def mkdir_p(dir): # -> None:
    ...

