"""
This type stub file was generated by pyright.
"""

'''
simple templating system for mavlink generator

Copyright Andrew Tridgell 2011
Released under GNU GPL version 3 or later
'''
class MAVTemplate:
    '''simple templating system'''
    def __init__(self, start_var_token=..., end_var_token=..., start_rep_token=..., end_rep_token=..., trim_leading_lf=..., checkmissing=...) -> None:
        ...
    
    def find_end(self, text, start_token, end_token, ignore_end_token=...): # -> int:
        '''find the of a token.
        Returns the offset in the string immediately after the matching end_token'''
        ...
    
    def find_var_end(self, text): # -> int:
        '''find the of a variable'''
        ...
    
    def find_rep_end(self, text): # -> int:
        '''find the of a repitition'''
        ...
    
    def substitute(self, text, subvars=..., trim_leading_lf=..., checkmissing=...):
        '''substitute variables in a string'''
        ...
    
    def write(self, file, text, subvars=..., trim_leading_lf=...): # -> None:
        '''write to a file with variable substitution'''
        ...
    


